@WebAPI_HostAddress = http://localhost:5122

GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{WebAPI_HostAddress}}/users
Accept: application/json

###

POST {{WebAPI_HostAddress}}/users
Content-Type: application/json
{
    "UserName": "Mimi",
    "PassWord": "mimi1234"
}
###
POST {{WebAPI_HostAddress}}/users
Content-Type: application/json
{
    "UserName": "Uwu",
    "PassWord": "uwu5678"
}
###

PUT {{WebAPI_HostAddress}}/users
Content-Type: application/json
{
    "UserId": "3",
    "UserName": "uwu8765"
}
###
PATCH {{WebAPI_HostAddress}}/users/updatepass/4
Content-Type: application/json
{
    "PassWord": "mimi0000"
}
###
PATCH {{WebAPI_HostAddress}}/users/updateusername/3
Content-Type: application/json
{
    "UserName": "NotUwu"
}
###

###
DELETE {{WebAPI_HostAddress}}/users/2

###

// post new user

GET {{WebAPI_HostAddress}}/posts
Accept: application/json
###
GET {{WebAPI_HostAddress}}/posts/2
Accept: application/json
###
PUT {{WebAPI_HostAddress}}/posts/2
Content-Type: application/json
{
    "Title": "changed",
    "Body": "yesyes"
}